{{- $chartName := .Chart.Name }}
{{- $releaseName := .Release.Name }}
{{- $values := .Values }}
{{- range $k, $v := $.Values.integrations }}
{{- if $v.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{- (printf "%s-%s" $releaseName .integrationKey) | trunc 63 | trimSuffix "-" }}"
stringData:
  appsettings.json: |-
    {
        "PloomesSecrets": {
            "DDService": "{{ $values.shared.appsettings.datadog.service }}-{{ .integrationKey }}",
            "DDTags": "{{ $values.shared.appsettings.datadog.tags }}",
            "DataDogPostUrl": "{{ $values.shared.appsettings.datadog.url }}",
            "HeaderDataDogApiKey": "{{ $values.shared.appsettings.datadog.apikey }}",
            "HeaderDataDogApiValue": "{{ $values.shared.appsettings.datadog.apivalue }}",
            "HeaderDataDogAppKey": "{{ $values.shared.appsettings.datadog.appkey }}",
            "HeaderDataDogAppValue": "{{ $values.shared.appsettings.datadog.appvalue }}",
            "KafkaTopic": "{{ $v.appsettings.kafkaConsumerTopic }}",
            "KafkaHost": "{{ $values.shared.appsettings.connectionstrings.kafka }}",
            "RedisConnectionString": "{{ $values.shared.appsettings.connectionstrings.redis }}",
            "ConnectionString": "{{ $values.shared.appsettings.connectionstrings.sqlserver }}",
            "SendGridApiKey": "{{ $values.shared.appsettings.sendgrid.apikey }}",
            "NeppoSemaphoreRetryDelaySeconds": {{ $values.shared.appsettings.neppo.semaphoreretrydelayseconds }}
        }
    }
---
{{- end }}
{{- end }}
