name: redeploy-prd
run-name: Redeploy latest tag PRD
on: [workflow_dispatch]

jobs:
  get_latest_tag:
    name: Get latest version tag
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.get_latest_tag.outputs.version-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Get latest tag
        id: get_latest_tag
        uses: Ploomes/DevOpsAtelier/actions/simple-versioning/get-latest-tag@main
        with:
          suffix: -prd
  redeploy:
    name: Redeploy to PRD enviroment
    needs: [get_latest_tag]
    uses: Ploomes/DevOpsAtelier/.github/workflows/dotnet-k8s-deploy-with-helm-to-azure-aks.yaml@main
    with:
      environment: prdBr
      keyvault-name: ${{ vars.KV_NAME_PRD }}
      keyvault-helm-value-secret-name: ${{ vars.KV_SECRET_NAME_HELM_VALUES_PRD }}
      k8s-namespace: ${{ vars.K8S_NAMESPACE_PRD }}
      helm-release-name: ${{ vars.HELM_RELEASE_NAME }}
      extra-helm-upgrade-args: --set version=${{ needs.get_latest_tag.outputs.latest-tag }}
      rr-entire-namespace: false
    secrets:
      az-credential: ${{ secrets.AZ_CREDENTIAL }}
      devops-github-token: ${{ secrets.GH_DEVOPS_TOKEN }}
