name: rollback-hml
run-name: Rollback HML
on: [workflow_dispatch]

jobs:
  rollback_versioning:
    name: Rollback tag versioning
    uses: Ploomes/DevOpsAtelier/.github/workflows/rollback-simple-versioning.yaml@main
    with:
      suffix: -hml
      devops-github-user: ${{ vars.GH_DEVOPS_USER }}
    secrets:
      devops-github-token: ${{ secrets.GH_DEVOPS_TOKEN }}
  rollback:
    name: Rollback to HML enviroment
    needs: [rollback_versioning]
    uses: Ploomes/DevOpsAtelier/.github/workflows/dotnet-k8s-deploy-with-helm-to-azure-aks-with-deployment.yaml@main
    with:
      environment: hml
      keyvault-name: ${{ vars.KV_NAME_HML }}
      keyvault-helm-value-secret-name: ${{ vars.KV_SECRET_NAME_HELM_VALUES_HML }}
      k8s-namespace: ${{ vars.K8S_NAMESPACE_HML }}
      helm-release-name: ${{ vars.HELM_RELEASE_NAME }}
      extra-helm-upgrade-args: --set version=${{ needs.rollback_versioning.outputs.last-active-version-tag }}
      rr-entire-namespace: false
    secrets:
      az-credential: ${{ secrets.AZ_CREDENTIAL_HML }}
      devops-github-token: ${{ secrets.GH_DEVOPS_TOKEN }}
